load("//:build/wd_rust_crate.bzl", "wd_rust_crate")

wd_rust_crate(
    name = "sandbox-executor",
    cxx_bridge_src = "lib.rs",
    visibility = ["//visibility:public"],
    deps = [
        "@crates_vendor//:base64",
        "@crates_vendor//:serde",
        "@crates_vendor//:serde_json",
        "@crates_vendor//:thiserror",
    ],
)
